### ISSUE TITLE
文字框被擋到了

### ISSUE THREAD

**Issue by kelvin0511** [jim60105/sound-buttons#12]
![image](https://user-images.githubusercontent.com/51434497/201962529-cb5a5cb7-56fc-412c-bc96-8ffbdabbcce5.png)

這是enomu165的版面中的自介文字
目前測試到的是把瀏覽器放愈大顯示出來的字會愈少
最小是100% 然後100%以下不變 一樣是沒有完全顯示

**Comment by jim60105** [comment]
我修改了一種RWD邏輯
如果還是會超出，建議減少文字內容
